services:

  # 1. PostgreSQL 16 + pgvector Store


  # 2. ASP.NET Core 8 Web API
  backend:
    image: 449513325212.dkr.ecr.ap-south-1.amazonaws.com/clausio-backend:latest
    container_name: clausio-backend-api
    restart: always
    ports:
      - "127.0.0.1:5123:5123"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:5123
      ConnectionStrings__Default: Host=database-1.cd2o4g4yqiiy.ap-south-1.rds.amazonaws.com;Port=5432;Database=clausio_db;Username=postgres;Password=${RDS_PASSWORD}
      AWS__Region: ap-south-1
      AWS__S3BucketName: clausio-files-prod
      AWS__SQSQueueUrl: https://sqs.ap-south-1.amazonaws.com/449513325212/clausio-ai-jobs
   

  # 3. Next.js 14 Web Frontend
  frontend:
    image: 449513325212.dkr.ecr.ap-south-1.amazonaws.com/clausio-frontend:latest
    container_name: clausio-frontend-web
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: /api
    depends_on:
      - backend

  # 4. Python Speech-to-Text Microservice
  voice-backend:
    image: 449513325212.dkr.ecr.ap-south-1.amazonaws.com/clausio-voice-backend:latest
    container_name: clausio-voice-microservice
    restart: always
    ports:
      - "127.0.0.1:8000:8000"

