'use client'

import { useState, useEffect } from 'react'

const STORAGE_KEY = 'clausio_ai_acknowledged'

export default function AIAcknowledgmentModal() {
  const [show, setShow] = useState(false)

  useEffect(() => {
    try {
      const acknowledged = localStorage.getItem(STORAGE_KEY)
      if (!acknowledged) setShow(true)
    } catch {}
  }, [])

  function handleAccept() {
    try { localStorage.setItem(STORAGE_KEY, 'true') } catch {}
    setShow(false)
  }

  if (!show) return null

  return (
    <div style={{
      position: 'fixed', inset: 0, zIndex: 99999,
      background: 'rgba(0,0,0,0.6)',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      padding: 20,
    }}>
      <div style={{
        background: '#fff', borderRadius: 20, padding: 32,
        maxWidth: 480, width: '100%',
        boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 20 }}>
          <div style={{ width: 44, height: 44, borderRadius: 12, background: '#fffbeb', border: '1px solid #fde68a', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 22, flexShrink: 0 }}>
            ⚖️
          </div>
          <div>
            <h2 style={{ margin: 0, fontSize: 18, fontWeight: 700, color: '#0f172a' }}>Important Notice</h2>
            <p style={{ margin: 0, fontSize: 12, color: '#64748b' }}>Please read before using Clausio AI</p>
          </div>
        </div>

        <div style={{ background: '#fffbeb', border: '1px solid #fde68a', borderRadius: 12, padding: 16, marginBottom: 20 }}>
          <p style={{ margin: 0, fontSize: 13, color: '#92400e', lineHeight: 1.7 }}>
            <strong>Clausio is an AI research assistant, not a legal advisor.</strong>
            <br /><br />
            All AI-generated content — including risk assessments, recommendations, legal research, hearing preparation, and action plans — is generated by artificial intelligence and <strong>must be independently verified</strong> by a qualified legal professional before use in court or legal proceedings.
            <br /><br />
            Clausio does not provide legal advice. The outputs are meant to assist advocates in research and preparation, not to replace professional legal judgment.
          </p>
        </div>

        <div style={{ fontSize: 12, color: '#64748b', marginBottom: 20, lineHeight: 1.6 }}>
          By clicking "I Understand", you acknowledge that you are a legal professional using this tool to assist your own independent legal judgment.
        </div>

        <button onClick={handleAccept} style={{
          width: '100%', padding: '14px', border: 'none', borderRadius: 12,
          background: '#2563eb', color: '#fff', fontWeight: 700, fontSize: 15,
          cursor: 'pointer', fontFamily: 'inherit',
        }}>
          I Understand — Continue to Clausio
        </button>
      </div>
    </div>
  )
}
