'use client'

interface DraftPreviewProps {
  draftType: string
  draft: any
  loading: boolean
}

export default function DraftPreview({
  draftType,
  draft,
  loading,
}: DraftPreviewProps) {
  if (loading) {
    return (
      <div
        className="glass-card"
        style={{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          padding: '80px 0',
          fontSize: 15,
          color: '#64748b',
          fontWeight: 500,
        }}
      >
        Generating legal draft...
      </div>
    )
  }

  return (
    <div
      className="glass-card"
      style={{
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      <div
        style={{
          padding: '18px 24px',
          borderBottom: '1px solid rgba(226,232,240,.8)',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
        }}
      >
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 10,
          }}
        >
          <i
            className="ti ti-file-text"
            style={{
              color: '#2563eb',
              fontSize: 18,
            }}
          />

          <span
            style={{
              fontWeight: 700,
              color: '#0f172a',
            }}
          >
            {draftType}
          </span>
        </div>

        {draft && (
          <span
            style={{
              fontSize: 12,
              color: '#64748b',
            }}
          >
            Generated just now
          </span>
        )}
      </div>

      <div
        style={{
          padding: 20,
        }}
      >
        <div
          style={{
            background: '#fff',
            borderRadius: 12,
            padding: '28px 36px',
            border: '1px solid #e2e8f0',
            lineHeight: 1.8,
            color: '#0f172a',
            width: '100%',
            maxWidth: 900,
            margin: '0 auto',
            boxShadow: '0 4px 16px rgba(15,23,42,.06)',
          }}
        >
          <div
            style={{
              textAlign: 'center',
              marginBottom: 32,
            }}
          >
            <h2
              style={{
                margin: 0,
                fontSize: 20,
              }}
            >
              {draftType}
            </h2>

            <p
              style={{
                marginTop: 10,
                color: '#64748b',
                fontSize: 13,
              }}
            >
              Generated by Clausio AI
            </p>
          </div>

          {draft ? (
            <>
              <p>
                This draft has been generated successfully.
              </p>

              <p>
                The backend integration will populate this document using
                chronology, evidence, legal issues, and strategic notes.
              </p>

              <p>
                Once the AI service is connected, this placeholder content
                will automatically be replaced by the generated petition,
                affidavit, written statement, bail application, or legal notice.
              </p>
            </>
          ) : (
            <div
              style={{
                textAlign: 'center',
                color: '#94a3b8',
                padding: '60px 0',
              }}
            >
              <i
                className="ti ti-file-description"
                style={{
                  fontSize: 48,
                  marginBottom: 16,
                }}
              />

              <h3
                style={{
                  marginBottom: 8,
                  color: '#334155',
                }}
              >
                No Draft Generated
              </h3>

              <p>
                Configure the draft on the left and click
                <strong> Generate Draft</strong>.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}